/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Fri Apr 22 19:11:14 2016. */

#ifndef PB_MCUCMDMSG_PB_H_INCLUDED
#define PB_MCUCMDMSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MotorCmd {
    bool has_num;
    int32_t num;
    bool has_dir;
    int32_t dir;
    bool has_degSec;
    double degSec;
    bool has_aDegSec;
    double aDegSec;
/* @@protoc_insertion_point(struct:MotorCmd) */
} MotorCmd;

typedef struct _SensorCmd {
    bool has_name;
    char name[32];
    bool has_value;
    double value;
    bool has_unit;
    char unit[32];
/* @@protoc_insertion_point(struct:SensorCmd) */
} SensorCmd;

typedef struct _McuWrapperMessage {
    pb_size_t which_msg;
    union {
        MotorCmd motorCmd;
        SensorCmd sensorCmd;
    } msg;
/* @@protoc_insertion_point(struct:McuWrapperMessage) */
} McuWrapperMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MotorCmd_init_default                    {false, 0, false, 0, false, 0, false, 0}
#define SensorCmd_init_default                   {false, "", false, 0, false, ""}
#define McuWrapperMessage_init_default           {0, {MotorCmd_init_default}}
#define MotorCmd_init_zero                       {false, 0, false, 0, false, 0, false, 0}
#define SensorCmd_init_zero                      {false, "", false, 0, false, ""}
#define McuWrapperMessage_init_zero              {0, {MotorCmd_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MotorCmd_num_tag                         1
#define MotorCmd_dir_tag                         2
#define MotorCmd_degSec_tag                      3
#define MotorCmd_aDegSec_tag                     4
#define SensorCmd_name_tag                       1
#define SensorCmd_value_tag                      2
#define SensorCmd_unit_tag                       3
#define McuWrapperMessage_motorCmd_tag           1
#define McuWrapperMessage_sensorCmd_tag          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MotorCmd_fields[5];
extern const pb_field_t SensorCmd_fields[4];
extern const pb_field_t McuWrapperMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define MotorCmd_size                            40
#define SensorCmd_size                           77
#define McuWrapperMessage_size                   79

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MCUCMDMSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
