/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Mon Apr 11 16:32:30 2016. */

#ifndef PB_MCUCMDMSG_PB_H_INCLUDED
#define PB_MCUCMDMSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Monitor {
    pb_callback_t sensorName;
    pb_callback_t sensorData;
/* @@protoc_insertion_point(struct:Monitor) */
} Monitor;

typedef struct _Motor {
    int32_t motorNumber;
    double degPerSec;
    double rotationDeg;
    double accelDegSec2;
/* @@protoc_insertion_point(struct:Motor) */
} Motor;

typedef struct _SensorData {
    pb_callback_t name;
    double value;
    pb_callback_t unit;
/* @@protoc_insertion_point(struct:SensorData) */
} SensorData;

typedef struct _McuWrapperMessage {
    pb_size_t which_msg;
    union {
        Motor motor;
        Monitor monitor;
    } msg;
/* @@protoc_insertion_point(struct:McuWrapperMessage) */
} McuWrapperMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Motor_init_default                       {0, 0, 0, 0}
#define SensorData_init_default                  {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Monitor_init_default                     {{{NULL}, NULL}, {{NULL}, NULL}}
#define McuWrapperMessage_init_default           {0, {Motor_init_default}}
#define Motor_init_zero                          {0, 0, 0, 0}
#define SensorData_init_zero                     {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define Monitor_init_zero                        {{{NULL}, NULL}, {{NULL}, NULL}}
#define McuWrapperMessage_init_zero              {0, {Motor_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Monitor_sensorName_tag                   1
#define Monitor_sensorData_tag                   2
#define Motor_motorNumber_tag                    1
#define Motor_degPerSec_tag                      2
#define Motor_rotationDeg_tag                    3
#define Motor_accelDegSec2_tag                   4
#define SensorData_name_tag                      1
#define SensorData_value_tag                     2
#define SensorData_unit_tag                      3
#define McuWrapperMessage_motor_tag              1
#define McuWrapperMessage_monitor_tag            2

/* Struct field encoding specification for nanopb */
extern const pb_field_t Motor_fields[5];
extern const pb_field_t SensorData_fields[4];
extern const pb_field_t Monitor_fields[3];
extern const pb_field_t McuWrapperMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define Motor_size                               38
/* SensorData_size depends on runtime parameters */
/* Monitor_size depends on runtime parameters */
/* McuWrapperMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MCUCMDMSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
