/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Sun Apr 17 21:22:55 2016. */

#ifndef PB_MCUCMDMSG_PB_H_INCLUDED
#define PB_MCUCMDMSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MotorCmd {
    bool has_motorNumber;
    int32_t motorNumber;
    bool has_degPerSec;
    double degPerSec;
    bool has_rotationDeg;
    double rotationDeg;
    bool has_accelDegSec2;
    double accelDegSec2;
/* @@protoc_insertion_point(struct:MotorCmd) */
} MotorCmd;

typedef struct _SensorData {
    bool has_name;
    char name[32];
    bool has_value;
    double value;
    bool has_unit;
    char unit[32];
/* @@protoc_insertion_point(struct:SensorData) */
} SensorData;

typedef struct _McuWrapperMessage {
    pb_size_t which_msg;
    union {
        MotorCmd motorCmd;
        SensorData sensorData;
    } msg;
/* @@protoc_insertion_point(struct:McuWrapperMessage) */
} McuWrapperMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MotorCmd_init_default                    {false, 0, false, 0, false, 0, false, 0}
#define SensorData_init_default                  {false, "", false, 0, false, ""}
#define McuWrapperMessage_init_default           {0, {MotorCmd_init_default}}
#define MotorCmd_init_zero                       {false, 0, false, 0, false, 0, false, 0}
#define SensorData_init_zero                     {false, "", false, 0, false, ""}
#define McuWrapperMessage_init_zero              {0, {MotorCmd_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MotorCmd_motorNumber_tag                 1
#define MotorCmd_degPerSec_tag                   2
#define MotorCmd_rotationDeg_tag                 3
#define MotorCmd_accelDegSec2_tag                4
#define SensorData_name_tag                      1
#define SensorData_value_tag                     2
#define SensorData_unit_tag                      3
#define McuWrapperMessage_motorCmd_tag           1
#define McuWrapperMessage_sensorData_tag         2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MotorCmd_fields[5];
extern const pb_field_t SensorData_fields[4];
extern const pb_field_t McuWrapperMessage_fields[3];

/* Maximum encoded size of messages (where known) */
#define MotorCmd_size                            38
#define SensorData_size                          77
#define McuWrapperMessage_size                   79

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MCUCMDMSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
