/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.6-dev at Mon Apr 11 16:38:45 2016. */

#ifndef PB_VCUCMDMSG_PB_H_INCLUDED
#define PB_VCUCMDMSG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Drive {
    int32_t velocity;
    pb_callback_t direction;
    double acceleration;
    double distance;
    bool has_edgeDistance;
    double edgeDistance;
    pb_callback_t edgeSide;
/* @@protoc_insertion_point(struct:Drive) */
} Drive;

typedef struct _Halt {
    double acceleration;
/* @@protoc_insertion_point(struct:Halt) */
} Halt;

typedef struct _Orbit {
    double velocity;
    pb_callback_t direction;
    double acceleration;
    double degrees;
/* @@protoc_insertion_point(struct:Orbit) */
} Orbit;

typedef struct _VcuWrapperMessage {
    pb_size_t which_msg;
    union {
        Drive drive;
        Orbit orbit;
        Halt halt;
    } msg;
/* @@protoc_insertion_point(struct:VcuWrapperMessage) */
} VcuWrapperMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Drive_init_default                       {0, {{NULL}, NULL}, 0, 0, false, 0, {{NULL}, NULL}}
#define Orbit_init_default                       {0, {{NULL}, NULL}, 0, 0}
#define Halt_init_default                        {0}
#define VcuWrapperMessage_init_default           {0, {Drive_init_default}}
#define Drive_init_zero                          {0, {{NULL}, NULL}, 0, 0, false, 0, {{NULL}, NULL}}
#define Orbit_init_zero                          {0, {{NULL}, NULL}, 0, 0}
#define Halt_init_zero                           {0}
#define VcuWrapperMessage_init_zero              {0, {Drive_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define Drive_velocity_tag                       1
#define Drive_direction_tag                      2
#define Drive_acceleration_tag                   3
#define Drive_distance_tag                       4
#define Drive_edgeDistance_tag                   5
#define Drive_edgeSide_tag                       6
#define Halt_acceleration_tag                    1
#define Orbit_velocity_tag                       1
#define Orbit_direction_tag                      2
#define Orbit_acceleration_tag                   3
#define Orbit_degrees_tag                        4
#define VcuWrapperMessage_drive_tag              1
#define VcuWrapperMessage_orbit_tag              2
#define VcuWrapperMessage_halt_tag               3

/* Struct field encoding specification for nanopb */
extern const pb_field_t Drive_fields[7];
extern const pb_field_t Orbit_fields[5];
extern const pb_field_t Halt_fields[2];
extern const pb_field_t VcuWrapperMessage_fields[4];

/* Maximum encoded size of messages (where known) */
/* Drive_size depends on runtime parameters */
/* Orbit_size depends on runtime parameters */
#define Halt_size                                9
/* VcuWrapperMessage_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define VCUCMDMSG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
