/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6-dev at Mon Apr 11 16:38:45 2016. */

#include "VcuCmdMsg.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Drive_fields[7] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Drive, velocity, velocity, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, Drive, direction, velocity, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, Drive, acceleration, direction, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, Drive, distance, acceleration, 0),
    PB_FIELD(  5, DOUBLE  , OPTIONAL, STATIC  , OTHER, Drive, edgeDistance, distance, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, CALLBACK, OTHER, Drive, edgeSide, edgeDistance, 0),
    PB_LAST_FIELD
};

const pb_field_t Orbit_fields[5] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, Orbit, velocity, velocity, 0),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, Orbit, direction, velocity, 0),
    PB_FIELD(  3, DOUBLE  , REQUIRED, STATIC  , OTHER, Orbit, acceleration, direction, 0),
    PB_FIELD(  4, DOUBLE  , REQUIRED, STATIC  , OTHER, Orbit, degrees, acceleration, 0),
    PB_LAST_FIELD
};

const pb_field_t Halt_fields[2] = {
    PB_FIELD(  1, DOUBLE  , REQUIRED, STATIC  , FIRST, Halt, acceleration, acceleration, 0),
    PB_LAST_FIELD
};

const pb_field_t VcuWrapperMessage_fields[4] = {
    PB_ONEOF_FIELD(msg,   1, MESSAGE , ONEOF, STATIC  , FIRST, VcuWrapperMessage, drive, drive, &Drive_fields),
    PB_ONEOF_FIELD(msg,   2, MESSAGE , ONEOF, STATIC  , FIRST, VcuWrapperMessage, orbit, orbit, &Orbit_fields),
    PB_ONEOF_FIELD(msg,   3, MESSAGE , ONEOF, STATIC  , FIRST, VcuWrapperMessage, halt, halt, &Halt_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(VcuWrapperMessage, msg.drive) < 65536 && pb_membersize(VcuWrapperMessage, msg.orbit) < 65536 && pb_membersize(VcuWrapperMessage, msg.halt) < 65536 && pb_membersize(VcuWrapperMessage, msg.drive) < 65536 && pb_membersize(VcuWrapperMessage, msg.orbit) < 65536 && pb_membersize(VcuWrapperMessage, msg.halt) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Drive_Orbit_Halt_VcuWrapperMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(VcuWrapperMessage, msg.drive) < 256 && pb_membersize(VcuWrapperMessage, msg.orbit) < 256 && pb_membersize(VcuWrapperMessage, msg.halt) < 256 && pb_membersize(VcuWrapperMessage, msg.drive) < 256 && pb_membersize(VcuWrapperMessage, msg.orbit) < 256 && pb_membersize(VcuWrapperMessage, msg.halt) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Drive_Orbit_Halt_VcuWrapperMessage)
#endif


/* On some platforms (such as AVR), double is really float.
 * These are not directly supported by nanopb, but see example_avr_double.
 * To get rid of this error, remove any double fields from your .proto.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)

/* @@protoc_insertion_point(eof) */
