# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: McuCmdMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='McuCmdMsg.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fMcuCmdMsg.proto\"E\n\x08MotorCmd\x12\x0b\n\x03num\x18\x01 \x01(\x05\x12\x0b\n\x03\x64ir\x18\x02 \x01(\x05\x12\x0e\n\x06\x64\x65gSec\x18\x03 \x01(\x01\x12\x0f\n\x07\x61\x44\x65gSec\x18\x04 \x01(\x01\"6\n\tSensorCmd\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\"Z\n\x11McuWrapperMessage\x12\x1d\n\x08motorCmd\x18\x01 \x01(\x0b\x32\t.MotorCmdH\x00\x12\x1f\n\tsensorCmd\x18\x02 \x01(\x0b\x32\n.SensorCmdH\x00\x42\x05\n\x03msgb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOTORCMD = _descriptor.Descriptor(
  name='MotorCmd',
  full_name='MotorCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='MotorCmd.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dir', full_name='MotorCmd.dir', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='degSec', full_name='MotorCmd.degSec', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='aDegSec', full_name='MotorCmd.aDegSec', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=88,
)


_SENSORCMD = _descriptor.Descriptor(
  name='SensorCmd',
  full_name='SensorCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SensorCmd.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorCmd.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='SensorCmd.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=144,
)


_MCUWRAPPERMESSAGE = _descriptor.Descriptor(
  name='McuWrapperMessage',
  full_name='McuWrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorCmd', full_name='McuWrapperMessage.motorCmd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorCmd', full_name='McuWrapperMessage.sensorCmd', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='McuWrapperMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=146,
  serialized_end=236,
)

_MCUWRAPPERMESSAGE.fields_by_name['motorCmd'].message_type = _MOTORCMD
_MCUWRAPPERMESSAGE.fields_by_name['sensorCmd'].message_type = _SENSORCMD
_MCUWRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _MCUWRAPPERMESSAGE.fields_by_name['motorCmd'])
_MCUWRAPPERMESSAGE.fields_by_name['motorCmd'].containing_oneof = _MCUWRAPPERMESSAGE.oneofs_by_name['msg']
_MCUWRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _MCUWRAPPERMESSAGE.fields_by_name['sensorCmd'])
_MCUWRAPPERMESSAGE.fields_by_name['sensorCmd'].containing_oneof = _MCUWRAPPERMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['MotorCmd'] = _MOTORCMD
DESCRIPTOR.message_types_by_name['SensorCmd'] = _SENSORCMD
DESCRIPTOR.message_types_by_name['McuWrapperMessage'] = _MCUWRAPPERMESSAGE

MotorCmd = _reflection.GeneratedProtocolMessageType('MotorCmd', (_message.Message,), dict(
  DESCRIPTOR = _MOTORCMD,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:MotorCmd)
  ))
_sym_db.RegisterMessage(MotorCmd)

SensorCmd = _reflection.GeneratedProtocolMessageType('SensorCmd', (_message.Message,), dict(
  DESCRIPTOR = _SENSORCMD,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:SensorCmd)
  ))
_sym_db.RegisterMessage(SensorCmd)

McuWrapperMessage = _reflection.GeneratedProtocolMessageType('McuWrapperMessage', (_message.Message,), dict(
  DESCRIPTOR = _MCUWRAPPERMESSAGE,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:McuWrapperMessage)
  ))
_sym_db.RegisterMessage(McuWrapperMessage)


# @@protoc_insertion_point(module_scope)
