# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: McuCmdMsg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='McuCmdMsg.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fMcuCmdMsg.proto\"]\n\x08MotorCmd\x12\x13\n\x0bmotorNumber\x18\x01 \x01(\x05\x12\x11\n\tdegPerSec\x18\x02 \x01(\x01\x12\x13\n\x0brotationDeg\x18\x03 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65lDegSec2\x18\x04 \x01(\x01\"7\n\nSensorData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x12\x0c\n\x04unit\x18\x03 \x01(\t\"\\\n\x11McuWrapperMessage\x12\x1d\n\x08motorCmd\x18\x01 \x01(\x0b\x32\t.MotorCmdH\x00\x12!\n\nsensorData\x18\x02 \x01(\x0b\x32\x0b.SensorDataH\x00\x42\x05\n\x03msgb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOTORCMD = _descriptor.Descriptor(
  name='MotorCmd',
  full_name='MotorCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorNumber', full_name='MotorCmd.motorNumber', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='degPerSec', full_name='MotorCmd.degPerSec', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rotationDeg', full_name='MotorCmd.rotationDeg', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelDegSec2', full_name='MotorCmd.accelDegSec2', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=112,
)


_SENSORDATA = _descriptor.Descriptor(
  name='SensorData',
  full_name='SensorData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SensorData.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SensorData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='SensorData.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=169,
)


_MCUWRAPPERMESSAGE = _descriptor.Descriptor(
  name='McuWrapperMessage',
  full_name='McuWrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motorCmd', full_name='McuWrapperMessage.motorCmd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sensorData', full_name='McuWrapperMessage.sensorData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='McuWrapperMessage.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=171,
  serialized_end=263,
)

_MCUWRAPPERMESSAGE.fields_by_name['motorCmd'].message_type = _MOTORCMD
_MCUWRAPPERMESSAGE.fields_by_name['sensorData'].message_type = _SENSORDATA
_MCUWRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _MCUWRAPPERMESSAGE.fields_by_name['motorCmd'])
_MCUWRAPPERMESSAGE.fields_by_name['motorCmd'].containing_oneof = _MCUWRAPPERMESSAGE.oneofs_by_name['msg']
_MCUWRAPPERMESSAGE.oneofs_by_name['msg'].fields.append(
  _MCUWRAPPERMESSAGE.fields_by_name['sensorData'])
_MCUWRAPPERMESSAGE.fields_by_name['sensorData'].containing_oneof = _MCUWRAPPERMESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['MotorCmd'] = _MOTORCMD
DESCRIPTOR.message_types_by_name['SensorData'] = _SENSORDATA
DESCRIPTOR.message_types_by_name['McuWrapperMessage'] = _MCUWRAPPERMESSAGE

MotorCmd = _reflection.GeneratedProtocolMessageType('MotorCmd', (_message.Message,), dict(
  DESCRIPTOR = _MOTORCMD,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:MotorCmd)
  ))
_sym_db.RegisterMessage(MotorCmd)

SensorData = _reflection.GeneratedProtocolMessageType('SensorData', (_message.Message,), dict(
  DESCRIPTOR = _SENSORDATA,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:SensorData)
  ))
_sym_db.RegisterMessage(SensorData)

McuWrapperMessage = _reflection.GeneratedProtocolMessageType('McuWrapperMessage', (_message.Message,), dict(
  DESCRIPTOR = _MCUWRAPPERMESSAGE,
  __module__ = 'McuCmdMsg_pb2'
  # @@protoc_insertion_point(class_scope:McuWrapperMessage)
  ))
_sym_db.RegisterMessage(McuWrapperMessage)


# @@protoc_insertion_point(module_scope)
