# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicledriveprotocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='vehicledriveprotocol.proto',
  package='',
  serialized_pb=_b('\n\x1avehicledriveprotocol.proto\"\x95\x01\n\x05\x44rive\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\x12\x16\n\x0e\x64rive_distance\x18\x02 \x02(\r\x12\x17\n\x0f\x62uffer_distance\x18\x03 \x01(\r\"%\n\tDirection\x12\x0b\n\x07\x46ORWARD\x10\x00\x12\x0b\n\x07REVERSE\x10\x01\"\x1b\n\x04Side\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\"R\n\x04Turn\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\x12\x0f\n\x07\x64\x65grees\x18\x02 \x02(\r\" \n\tDirection\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\"\'\n\x0cRequestState\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\"\x1f\n\x04Halt\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\"\xe9\x01\n\x0c\x43urrentState\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\x12\x1b\n\x13left_rotary_encoder\x18\x02 \x01(\x01\x12\x1c\n\x14right_rotary_encoder\x18\x03 \x01(\x01\x12\x1c\n\x14left_buffer_distance\x18\x04 \x01(\r\x12\x1d\n\x15right_buffer_distance\x18\x05 \x01(\r\x12\x17\n\x0f\x63ompass_heading\x18\x06 \x01(\x01\"/\n\x05State\x12\x0c\n\x08NO_ERROR\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\r\n\tIN_MOTION\x10\x02\"\xde\x01\n\x11OperationFinished\x12\x17\n\x0fsequence_number\x18\x01 \x02(\r\x12\x1b\n\x13traveled_distance_x\x18\x02 \x01(\r\x12\x1b\n\x13traveled_distance_y\x18\x03 \x01(\r\x12\x1c\n\x14left_buffer_distance\x18\x04 \x01(\r\x12\x1d\n\x15right_buffer_distance\x18\x05 \x01(\r\x12\x13\n\x0binterrupted\x18\x06 \x01(\x08\"$\n\x05\x45rror\x12\x0c\n\x08NO_ERROR\x10\x00\x12\r\n\tSHELF_END\x10\x01\x42\x13\x42\x11VehicleDriveProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DRIVE_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='Drive.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORWARD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=114,
  serialized_end=151,
)
_sym_db.RegisterEnumDescriptor(_DRIVE_DIRECTION)

_DRIVE_SIDE = _descriptor.EnumDescriptor(
  name='Side',
  full_name='Drive.Side',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=153,
  serialized_end=180,
)
_sym_db.RegisterEnumDescriptor(_DRIVE_SIDE)

_TURN_DIRECTION = _descriptor.EnumDescriptor(
  name='Direction',
  full_name='Turn.Direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=232,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_TURN_DIRECTION)

_CURRENTSTATE_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='CurrentState.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IN_MOTION', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=527,
  serialized_end=574,
)
_sym_db.RegisterEnumDescriptor(_CURRENTSTATE_STATE)

_OPERATIONFINISHED_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='OperationFinished.Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_ERROR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SHELF_END', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=763,
  serialized_end=799,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONFINISHED_ERROR)


_DRIVE = _descriptor.Descriptor(
  name='Drive',
  full_name='Drive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='Drive.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drive_distance', full_name='Drive.drive_distance', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buffer_distance', full_name='Drive.buffer_distance', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DRIVE_DIRECTION,
    _DRIVE_SIDE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=180,
)


_TURN = _descriptor.Descriptor(
  name='Turn',
  full_name='Turn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='Turn.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='degrees', full_name='Turn.degrees', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TURN_DIRECTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=264,
)


_REQUESTSTATE = _descriptor.Descriptor(
  name='RequestState',
  full_name='RequestState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='RequestState.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=305,
)


_HALT = _descriptor.Descriptor(
  name='Halt',
  full_name='Halt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='Halt.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=338,
)


_CURRENTSTATE = _descriptor.Descriptor(
  name='CurrentState',
  full_name='CurrentState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='CurrentState.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_rotary_encoder', full_name='CurrentState.left_rotary_encoder', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_rotary_encoder', full_name='CurrentState.right_rotary_encoder', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_buffer_distance', full_name='CurrentState.left_buffer_distance', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_buffer_distance', full_name='CurrentState.right_buffer_distance', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compass_heading', full_name='CurrentState.compass_heading', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURRENTSTATE_STATE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=574,
)


_OPERATIONFINISHED = _descriptor.Descriptor(
  name='OperationFinished',
  full_name='OperationFinished',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequence_number', full_name='OperationFinished.sequence_number', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traveled_distance_x', full_name='OperationFinished.traveled_distance_x', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='traveled_distance_y', full_name='OperationFinished.traveled_distance_y', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='left_buffer_distance', full_name='OperationFinished.left_buffer_distance', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right_buffer_distance', full_name='OperationFinished.right_buffer_distance', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interrupted', full_name='OperationFinished.interrupted', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _OPERATIONFINISHED_ERROR,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=577,
  serialized_end=799,
)

_DRIVE_DIRECTION.containing_type = _DRIVE
_DRIVE_SIDE.containing_type = _DRIVE
_TURN_DIRECTION.containing_type = _TURN
_CURRENTSTATE_STATE.containing_type = _CURRENTSTATE
_OPERATIONFINISHED_ERROR.containing_type = _OPERATIONFINISHED
DESCRIPTOR.message_types_by_name['Drive'] = _DRIVE
DESCRIPTOR.message_types_by_name['Turn'] = _TURN
DESCRIPTOR.message_types_by_name['RequestState'] = _REQUESTSTATE
DESCRIPTOR.message_types_by_name['Halt'] = _HALT
DESCRIPTOR.message_types_by_name['CurrentState'] = _CURRENTSTATE
DESCRIPTOR.message_types_by_name['OperationFinished'] = _OPERATIONFINISHED

Drive = _reflection.GeneratedProtocolMessageType('Drive', (_message.Message,), dict(
  DESCRIPTOR = _DRIVE,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:Drive)
  ))
_sym_db.RegisterMessage(Drive)

Turn = _reflection.GeneratedProtocolMessageType('Turn', (_message.Message,), dict(
  DESCRIPTOR = _TURN,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:Turn)
  ))
_sym_db.RegisterMessage(Turn)

RequestState = _reflection.GeneratedProtocolMessageType('RequestState', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTSTATE,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:RequestState)
  ))
_sym_db.RegisterMessage(RequestState)

Halt = _reflection.GeneratedProtocolMessageType('Halt', (_message.Message,), dict(
  DESCRIPTOR = _HALT,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:Halt)
  ))
_sym_db.RegisterMessage(Halt)

CurrentState = _reflection.GeneratedProtocolMessageType('CurrentState', (_message.Message,), dict(
  DESCRIPTOR = _CURRENTSTATE,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:CurrentState)
  ))
_sym_db.RegisterMessage(CurrentState)

OperationFinished = _reflection.GeneratedProtocolMessageType('OperationFinished', (_message.Message,), dict(
  DESCRIPTOR = _OPERATIONFINISHED,
  __module__ = 'vehicledriveprotocol_pb2'
  # @@protoc_insertion_point(class_scope:OperationFinished)
  ))
_sym_db.RegisterMessage(OperationFinished)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('B\021VehicleDriveProto'))
# @@protoc_insertion_point(module_scope)
